version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: pos1234
    volumes:
      - pgdata:/var/lib/posgresql/data
  shortener:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./urlshortener:/urlshortener
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
volumes:
  pgdata: