version: "3"
services:
  db:
    image: postgres
    container_name: post_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: pos1234
    volumes:
      - pgdata:/var/lib/postgresql/data
  shortener:
    container_name: urlshortener
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./.env:/urlshortener/.env
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
volumes:
  pgdata: